services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=tuum'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'